In [32]:
from sklearn.preprocessing import MinMaxScaler
re = MinMaxScaler()

In [31]:
# from sklearn import preprocessing
# re = preprocessing.MinMaxScaler()

In [34]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
print(re.fit(data))

MinMaxScaler()


In [35]:
print(re.data_max_)

[ 1. 18.]


In [36]:
print(re.transform(data))

[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


In [33]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder().fit([1,2,2,6])
le

LabelEncoder()

In [9]:
le.classes_

array([1, 2, 6])

In [12]:
le.transform([1,6,2,1,2,6])

array([0, 2, 1, 0, 1, 2])

In [ ]:

>>> le.classes_
array([1, 2, 6])
>>> le.transform([1, 1, 2, 6])
array([0, 0, 1, 2]...)
>>> le.inverse_transform([0, 0, 1, 2])
array([1, 1, 2, 6])


In [16]:
le = preprocessing.LabelEncoder()

In [18]:
le.fit_transform([35,57,72,94,11,33,25])

array([3, 4, 5, 6, 0, 2, 1])

In [21]:
dir(preprocessing)

['Binarizer',
 'FunctionTransformer',
 'KBinsDiscretizer',
 'KernelCenterer',
 'LabelBinarizer',
 'LabelEncoder',
 'MaxAbsScaler',
 'MinMaxScaler',
 'MultiLabelBinarizer',
 'Normalizer',
 'OneHotEncoder',
 'OrdinalEncoder',
 'PolynomialFeatures',
 'PowerTransformer',
 'QuantileTransformer',
 'RobustScaler',
 'StandardScaler',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_csr_polynomial_expansion',
 '_data',
 '_discretization',
 '_encoders',
 '_function_transformer',
 '_label',
 'add_dummy_feature',
 'binarize',
 'label_binarize',
 'maxabs_scale',
 'minmax_scale',
 'normalize',
 'power_transform',
 'quantile_transform',
 'robust_scale',
 'scale']